version: "3.1"

services:
  #  spring-boot:
  #    build: ./
  #    ports:
  #      - "8080:8080"
  #   health check:
  #      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 5
  #    environment:
  #      PROFILE: dev


  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-config/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d spring" ]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: